#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Tue Mar 17 00:28:25 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class ServerManagerFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ServerManagerFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_root = wx.Panel(self, -1)
        self.panel_log = wx.Panel(self.panel_root, -1)
        self.panel_buttons = wx.Panel(self.panel_root, -1)
        self.button_start = wx.ToggleButton(self.panel_buttons, -1, "Start")
        self.button_stop = wx.ToggleButton(self.panel_buttons, -1, "Stop")
        self.button_hosts = wx.Button(self.panel_buttons, -1, "Hosts Editor")
        self.text_ctrl_log = wx.TextCtrl(self.panel_log, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.HSCROLL|wx.TE_LINEWRAP|wx.TE_WORDWRAP)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOGGLEBUTTON, self.StartServer, self.button_start)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.StopServer, self.button_stop)
        self.Bind(wx.EVT_BUTTON, self.OnHostsButton, self.button_hosts)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ServerManagerFrame.__set_properties
        self.SetTitle("TeknoGods Server Emulator")
        self.button_stop.SetValue(1)
        self.panel_root.SetMinSize((472, 189))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ServerManagerFrame.__do_layout
        sizer_root = wx.BoxSizer(wx.VERTICAL)
        sizer_subroot = wx.BoxSizer(wx.VERTICAL)
        sizer_log = wx.BoxSizer(wx.HORIZONTAL)
        sizer_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_buttons.Add(self.button_start, 0, 0, 0)
        sizer_buttons.Add(self.button_stop, 0, 0, 0)
        sizer_buttons.Add(self.button_hosts, 0, 0, 0)
        self.panel_buttons.SetSizer(sizer_buttons)
        sizer_subroot.Add(self.panel_buttons, 0, wx.EXPAND, 0)
        sizer_log.Add(self.text_ctrl_log, 1, wx.EXPAND, 0)
        self.panel_log.SetSizer(sizer_log)
        sizer_subroot.Add(self.panel_log, 1, wx.EXPAND, 0)
        self.panel_root.SetSizer(sizer_subroot)
        sizer_root.Add(self.panel_root, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_root)
        sizer_root.Fit(self)
        sizer_root.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def StartServer(self, event): # wxGlade: ServerManagerFrame.<event_handler>
        print "Event handler `StartServer' not implemented!"
        event.Skip()

    def StopServer(self, event): # wxGlade: ServerManagerFrame.<event_handler>
        print "Event handler `StopServer' not implemented!"
        event.Skip()

    def OnHostsButton(self, event): # wxGlade: ServerManagerFrame.<event_handler>
        print "Event handler `OnHostsButton' not implemented!"
        event.Skip()

# end of class ServerManagerFrame


class HostsDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: HostsDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.window_1 = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_1_pane_2 = wx.Panel(self.window_1, -1)
        self.window_1_pane_1 = wx.Panel(self.window_1, -1)
        self.sizer_11_staticbox = wx.StaticBox(self.window_1_pane_2, -1, "Hosts")
        self.sizer_10_staticbox = wx.StaticBox(self.window_1_pane_1, -1, "Groups")
        self.button_enable = wx.ToggleButton(self, -1, "Enable")
        self.button_disable = wx.ToggleButton(self, -1, "Disable")
        self.label_2 = wx.StaticText(self, -1, "IP", style=wx.ALIGN_RIGHT)
        self.text_ctrl_ip = wx.TextCtrl(self, -1, "127.0.0.1")
        self.list_box_groups = wx.CheckListBox(self.window_1_pane_1, -1, choices=[])
        self.list_box_hosts = wx.CheckListBox(self.window_1_pane_2, -1, choices=[])

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX, self.OnGroupClick, self.list_box_groups)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: HostsDialog.__set_properties
        self.SetTitle("Hosts Editor")
        self.SetSize((423, 323))
        self.button_enable.Enable(False)
        self.button_disable.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: HostsDialog.__do_layout
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.StaticBoxSizer(self.sizer_11_staticbox, wx.HORIZONTAL)
        sizer_10 = wx.StaticBoxSizer(self.sizer_10_staticbox, wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6.Add(self.button_enable, 0, 0, 0)
        sizer_6.Add(self.button_disable, 0, 0, 0)
        sizer_6.Add(self.label_2, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.text_ctrl_ip, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_10.Add(self.list_box_groups, 1, wx.EXPAND, 0)
        self.window_1_pane_1.SetSizer(sizer_10)
        sizer_11.Add(self.list_box_hosts, 1, wx.EXPAND, 0)
        self.window_1_pane_2.SetSizer(sizer_11)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
        sizer_7.Add(self.window_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_7)
        self.Layout()
        # end wxGlade

    def OnGroupClick(self, event): # wxGlade: HostsDialog.<event_handler>
        print "Event handler `OnGroupClick' not implemented!"
        event.Skip()

# end of class HostsDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_main = ServerManagerFrame(None, -1, "")
    app.SetTopWindow(frame_main)
    frame_main.Show()
    app.MainLoop()
