#!/usr/bin/python
import sys
import os
from subprocess import *

modFile = 'eaEmu/dj/eaEmu/models.py'
f = open(modFile, 'w')
f.write('from django.db import models\n\n')
f.close()
prefix = os.path.dirname(sys.argv[0])
cmd = ' '.join([
      os.path.join(prefix, 'dia2django.py'),
      os.path.join(prefix, 'eaEmu.dia'),
      '>>',
      modFile
])
Popen(cmd, shell=True).wait()
